---
name: 提交新需求
description: 新功能需求模板
labels: ["feature"]
body:
  - type: checkboxes
    attributes:
      label: 提需求之前，请先确认
      description: "请检查以下确认项"
      options:
        - label: "已经阅读过Q&A (https://musicfree.catcat.work/qa/mobile.html)"
          required: true
        - label: "新需求不是仅仅满足个人口味的需求"
          required: true
        - label: "新需求不与其他已有issue重复"
          required: true
        - label: "我可以在代码、测试上提供帮助"
          required: false

  - type: textarea
    id: feature_description
    attributes:
      label: 需求描述
      description: "请详细说明需求背景、使用场景和预期效果"
      placeholder: |
        例如：
        - 当前存在的痛点是什么？
        - 希望如何解决这个问题？
        - 预期的使用体验是怎样的？
    validations:
      required: true

  - type: textarea
    id: attachments
    attributes:
      label: 附件信息（可选）
      description: "可拖放上传示意图/设计稿"
      placeholder: "设计稿说明或云文档链接..."
    validations:
      required: false
